export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const APPROVE_PRODUCT_REQUEST = "APPROVE_PRODUCT_REQUEST";
export const APPROVE_PRODUCT_SUCCESS = "APPROVE_PRODUCT_SUCCESS";
export const APPROVE_PRODUCT_RESET = "APPROVE_PRODUCT_RESET";
export const APPROVE_PRODUCT_FAIL = "APPROVE_PRODUCT_FAIL";

export const AVAILABLE_PRODUCT_REQUEST = "AVAILABLE_PRODUCT_REQUEST";
export const AVAILABLE_PRODUCT_SUCCESS = "AVAILABLE_PRODUCT_SUCCESS";
export const AVAILABLE_PRODUCT_RESET = "AVAILABLE_PRODUCT_RESET";
export const AVAILABLE_PRODUCT_FAIL = "AVAILABLE_PRODUCT_FAIL";

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";