export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const  PRODUCT_APPROVE_REQUEST = "PRODUCT_APPROVE_REQUEST";
export const  PRODUCT_APPROVE_SUCCESS = "PRODUCT_APPROVE_SUCCESS";
export const  PRODUCT_APPROVE_FAIL = "PRODUCT_APPROVE_FAIL";
export const  PRODUCT_APPROVE_RESET = "PRODUCT_APPROVE_RESET";

export const  PRODUCT_AVAILABLE_REQUEST = "PRODUCT_AVAILABLE_REQUEST";
export const  PRODUCT_AVAILABLE_SUCCESS = "PRODUCT_AVAILABLE_SUCCESS";
export const  PRODUCT_AVAILABLE_FAIL = "PRODUCT_AVAILABLE_FAIL";
export const  PRODUCT_AVAILABLE_RESET = "PRODUCT_AVAILABLE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";