export const   APPLY_SELLER_REQUEST = "APPLY_SELLER_REQUEST";
export const   APPLY_SELLER_SECCESS = "APPLY_SELLER_SECCESS";
export const   APPLY_SELLER_FAIL = "APPLY_SELLER_FAIL";
export const   APPLY_SELLER_RESET = "APPLY_SELLER_RESET";

export const ADMIN_APPLICATION_REQUEST = "ADMIN_APPLICATION_REQUEST";
export const ADMIN_APPLICATION_SUCCESS = "ADMIN_APPLICATION_SUCCESS";
export const ADMIN_APPLICATION_FAIL = "ADMIN_APPLICATION_FAIL";

export const APPLICATION_DETAILS_REQUEST = "APPLICATION_DETAILS_REQUEST";
export const APPLICATION_DETAILS_SUCCESS = "APPLICATION_DETAILS_SUCCESS";
export const APPLICATION_DETAILS_FAIL = "APPLICATION_DETAILS_FAIL";

export const REMOVE_APPLICATION_DETAILS = "REMOVE_APPLICATION_DETAILS";

export const UPDATE_APPLICATION_STATUS_REQUEST = "UPDATE_APPLICATION_STATUS_REQUEST";
export const UPDATE_APPLICATION_STATUS_SUCCESS = "UPDATE_APPLICATION_STATUS_SUCCESS";
export const UPDATE_APPLICATION_STATUS_RESET = "UPDATE_APPLICATION_STATUS_RESET";
export const UPDATE_APPLICATION_STATUS_FAIL = "UPDATE_APPLICATION_STATUS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";