export const  REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const  REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const  REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"; 
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"; 
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"; 

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FALI";

export const OTP_SEND_REQUEST = "OTP_SEND_REQUEST";
export const OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS";
export const OTP_SEND_FAIL = "OTP_SEND_FAIL";

export const OTP_LOGIN_REQUEST = "OTP_LOGIN_REQUEST";
export const OTP_LOGIN_SUCCESS = "OTP_LOGIN_SUCCESS";
export const OTP_LOGIN_FAIL = "OTP_LOGIN_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"; 
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"; 
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"; 
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"; 

export const CLEAR_ERRORS = "CLEAR_ERRORS";